blog/urls.py
from django.urls import (
    path,
)
from .views import *


urlpatterns = [
    path('', PostListView.as_view(), name='blog_index'),
    path('<category>/', CategoryPostView.as_view(), name='blog_category'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='blog_detail'),
    path('post/<int:pk>/comment/create/', CommentCreateView.as_view(), name='comment_create'),
]

source/urls.py
from django.contrib import (
    admin,
)
from django.urls import (
    include, 
    path,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('api/blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('api/todo_list/', include(('todo_app.urls', 'todo_app'), namespace='todo_app')),
    path('api/diary/', include(('diary_app.urls', 'diary_app'), namespace='diary_app')),
    path('api/flashcards/', include(('cardapp.urls', 'cardapp'), namespace='cardapp')),
    path('api/content/aggregator/', include(('content_aggregator_app.urls', 'content_aggregator_app'), namespace='content_aggregator_app')),
]

blog/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=20)

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')

class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

blog/forms.py
from django import (
    forms,
)

class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )

blog/views.py
from rest_framework.response import (
    Response,
)
from rest_framework import (
    generics,
) 
from rest_framework.views import (
    APIView,
    )
from rest_framework import (
    permissions,
    )
from .models import (
    Comment,
    Post,
)
from .serializers import (
    PostSerializer,
    CommentSerializer,
)


class CategoryPostView(generics.RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset().filter(categories__name=self.kwargs['category'])
        serializer = self.get_serializer(queryset, many=True)
        context = {'posts': serializer.data}
        return Response(context)
    
class PostListView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True)
        context = {'posts': serializer.data}
        return Response(context)

class PostDetailView(APIView):
    permission_classes = [permissions.DjangoModelPermissionsOrAnonReadOnly]
    queryset = Post.objects.all()

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        comments = Comment.objects.filter(post=post)
        post_serializer = PostSerializer(post)
        comments_serializer = CommentSerializer(comments, many=True)
        data = {
            'post': post_serializer.data,
            'comments': comments_serializer.data,
        }
        return Response(data)
    
    def get_object(self):
        id = self.kwargs.get('pk')
        post = Post.objects.get(id=id)
        return post

class CommentCreateView(APIView):
    permission_classes = [permissions.IsAuthenticated]

    def post(self, request, *args, **kwargs):
        serializer = CommentSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(serializer.errors, status=400)

blog/templates/blog_category.html
{% extends "base.html" %}
{% block page_content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ category | title }}</h1>
    <hr>
    {% for post in posts %}
    <h2><a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories %}
            <a href="{% url 'blog:blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog_detail.html
{% extends "base.html" %}
{% block page_content %}
<div class="col-md-8 offset-md-2">
    <h2><a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a></h2>
    <small>
        {{ post.created_on }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories %}
        <a href="{% url 'blog:blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Leave a comment:</h3>
    <form action="{% url 'blog:blog_detail' post.id %}" method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog_index.html
{% extends "base.html" %}
{% block page_content %}
{% if messages %}
<ul class="messages" style="background-color:#ccc">
{% for message in messages %}
<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
  {{ message }}
</li>
{% endfor %}
</ul>
{% endif %}
<div class="col-md-8 offset-md-2">
    <h1>Blog Index</h1>
    <hr>
    {% for post in posts %}
    <h2><a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a></h2>
    <small>
        {{ post.created_on }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories %}
            <a href="{% url 'blog:blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}