blog/urls.py
from django.urls import (
    path,
)
from .views import *


urlpatterns = [
    path('', PostListView.as_view(), name='blog_index'),
    path('<category>/', CategoryPostView.as_view(), name='blog_category'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='blog_detail'),
    path('post/<int:pk>/comment/create/', CommentCreateView.as_view(), name='comment_create'),
]

projects/urls.py
from django.urls import (
    include, 
    path,
)
from django.conf import settings
from django.conf.urls.static import static
from projects.views import *


urlpatterns = [
    path('', ProjectIndexView.as_view(), name='project_index'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

source/urls.py
from django.contrib import (
    admin,
)
from django.urls import (
    include, 
    path,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('api/blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('api/todo_list/', include(('todo_app.urls', 'todo_app'), namespace='todo_app')),
    path('api/diary/', include(('diary_app.urls', 'diary_app'), namespace='diary_app')),
    path('api/flashcards/', include(('cardapp.urls', 'cardapp'), namespace='cardapp')),
    path('api/content/aggregator/', include(('content_aggregator_app.urls', 'content_aggregator_app'), namespace='content_aggregator_app')),
]

source/templates/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'projects:project_index' %}">RP Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:project_index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:blog_index' %}">Blog</a>
            </li>
          </ul>
        </div>
    </div>

</nav>

<div class="container">
    {% block page_content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>