blog/urls.py
from django.urls import (
    path,
)
from .views import *


urlpatterns = [
    path('', PostListView.as_view(), name='blog_index'),
    path('<category>/', CategoryPostView.as_view(), name='blog_category'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='blog_detail'),
    path('post/<int:pk>/comment/create/', CommentCreateView.as_view(), name='comment_create'),
]

projects/urls.py
from django.urls import (
    include, 
    path,
)
from django.conf import settings
from django.conf.urls.static import static
from projects.views import *


urlpatterns = [
    path('', ProjectIndexView.as_view(), name='project_index'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

source/urls.py
from django.contrib import (
    admin,
)
from django.urls import (
    include, 
    path,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/projects/', include(('projects.urls', 'projects'), namespace='projects')),
    path('api/blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('api/todo_list/', include(('todo_app.urls', 'todo_app'), namespace='todo_app')),
    path('api/diary/', include(('diary_app.urls', 'diary_app'), namespace='diary_app')),
    path('api/flashcards/', include(('cardapp.urls', 'cardapp'), namespace='cardapp')),
    path('api/content/aggregator/', include(('content_aggregator_app.urls', 'content_aggregator_app'), namespace='content_aggregator_app')),
]

projects/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.FilePathField(path="projects/static/img/")

projects/views.py
from rest_framework.response import (
    Response,
)
from rest_framework import (
    generics,
)
from rest_framework.renderers import (
    TemplateHTMLRenderer,
)
from .models import (
    Project,
)
from .serializers import (
    ProjectSerializer,
)


class ProjectIndexView(generics.ListAPIView):
    queryset = Project.objects.all().order_by('id')
    serializer_class = ProjectSerializer

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True)
        context = {'projects': serializer.data}
        return Response(context)

class ProjectDetailView(generics.RetrieveAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    lookup_field = 'pk'

    def get(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        context = {'project': serializer.data}
        return Response(context)
    

projects/templates/project_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_content %}
<h1>{{ project.title }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="{% static project.image %}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the project:</h5>
        <p>{{ project.description }}</p>
        <br>
        <h5>Technology used:</h5>
        <p>{{ project.technology }}</p>
    </div>
</div>
{% endblock %}

projects/templates/project_index.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<h1>Projects</h1>
<div class="row">
{% for project in projects %}
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static project.image %}">
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                <a href="{% url 'projects:project_detail' project.id %}"
                   class="btn btn-primary">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}